- name: aws provison play
  hosts: localhost
  tasks:
    - name: Launch ec2 instance
      ec2:
        aws_access_key: <your aws_access_key>
        aws_secret_key: <your aws_secret_key>
        region: <your aws_region>
        key_name: <your aws-key>
        instance_type: t2.micro #change if you want bigger machine
        image: ami-a9aa74d1 #change with your amazon machine image id having python installed
        wait: yes
        group: <your aws_security_group>
        count: 1 #change if you want to launch more instances
        vpc_subnet_id: subnet-994badc2
        assign_public_ip: yes
      register: ec2

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
      with_items: "{{ ec2.instances }}"